<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RetypePassword</name>
   <tag></tag>
   <elementGuidId>aed1594f-11ad-4c99-83a5-8d34e0534809</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#retype_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='retype_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a77ea85-cfb2-4f8f-a72d-51ad8c404916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>74bd6279-37dc-4cc9-b186-8751cab6be40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>retype_password</value>
      <webElementGuid>163f05fd-bc09-4614-93d8-40770c22f561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>retype_password</value>
      <webElementGuid>7c380984-7aa9-4d9d-aee7-a804ba26897c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f9857191-e9b3-4c68-9170-7750537a41bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1cb91d5c-1794-4777-8514-06d57047c34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rule-equalto</name>
      <type>Main</type>
      <value>#password</value>
      <webElementGuid>bdc42a71-4642-4cbe-9a16-4fc66ce228ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg-equalto</name>
      <type>Main</type>
      <value>Please enter the same value again.</value>
      <webElementGuid>22182709-96c6-4b48-8fa1-ddbc9afb588d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;retype_password&quot;)</value>
      <webElementGuid>ff40b49c-920e-47e7-be4e-554ec6c94e72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='retype_password']</value>
      <webElementGuid>00ceef83-3c3f-4653-bfbe-966b7336abc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signup-form']/div[7]/div/input</value>
      <webElementGuid>8cfd85c0-ba59-4f7a-9e3d-bb0ea002c2a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>69009b9f-e455-4170-9aa5-b16ce0b14c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'retype_password' and @id = 'retype_password']</value>
      <webElementGuid>407c61e2-19a5-4ffe-b057-dcab99cadab3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
