<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_RetypePasswordError</name>
   <tag></tag>
   <elementGuidId>7d054a1c-b945-476c-a027-fc92c708e9a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#retype_password-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='retype_password-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4d7803ad-f67b-4857-9297-df385d20d4b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>retype_password-error</value>
      <webElementGuid>8b35d567-5bd3-448a-8f25-75f13082f0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help-block</value>
      <webElementGuid>10584391-3e46-40ea-b5cf-fd5be3a83eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter the same value again.</value>
      <webElementGuid>5f86ba0f-f99b-408d-99ca-140034d22ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;retype_password-error&quot;)</value>
      <webElementGuid>43f0a09e-5ed7-4529-bee2-c384c9dc9d9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='retype_password-error']</value>
      <webElementGuid>35ffae31-0261-49e0-9c37-8fe01deea750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signup-form']/div[7]/div/span</value>
      <webElementGuid>e5f91398-0f4f-481a-87c7-b511a4cfd9ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retype password'])[1]/following::span[1]</value>
      <webElementGuid>eb65ce78-6b8e-4cbd-a2da-66ccf44e753d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::span[1]</value>
      <webElementGuid>a3b5cae0-3be1-498a-81d2-284e8a33db24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[2]/preceding::span[1]</value>
      <webElementGuid>ea72627c-c8cb-4409-950e-bf1b14871b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please enter the same value again.']/parent::*</value>
      <webElementGuid>fef644e5-3548-4b19-9be8-9f746b06530d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>116ca235-e114-4cf1-8f3e-d2ec14817201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'retype_password-error' and (text() = 'Please enter the same value again.' or . = 'Please enter the same value again.')]</value>
      <webElementGuid>3fbf5ec0-adb3-4565-867c-21926e8ae683</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
