<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_AddMember</name>
   <tag></tag>
   <elementGuidId>b823ab20-192a-40ad-9b9e-24b4b0c236eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-default.float-end.add-member-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='project-overview-section']/div/div/div/div/div[5]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6d74f9e4-7a9a-4c64-b740-962362490da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>639b7b57-8fa5-4d4f-8c3f-703bcb7941d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default float-end add-member-button</value>
      <webElementGuid>bf18e1bc-508e-4c60-aa1f-33eec5fce2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add member</value>
      <webElementGuid>58bf3d3f-38b0-4db8-b36f-a6291bfa1f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-post-project_id</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>5146e923-642f-4443-b066-d785382e630e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-act</name>
      <type>Main</type>
      <value>ajax-modal</value>
      <webElementGuid>eebbf6da-ca8d-4283-bba5-94b4605f50bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Add member</value>
      <webElementGuid>b0ea175d-7adc-45bf-b9b7-b38caa437db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-url</name>
      <type>Main</type>
      <value>https://rise.fairsketch.com/index.php/projects/project_member_modal_form</value>
      <webElementGuid>80967188-f755-4644-98cc-499944619434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add member</value>
      <webElementGuid>65863dac-c4d1-466a-87a6-d68a9e2fa90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;project-overview-section&quot;)/div[@class=&quot;clearfix default-bg&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-sm-12&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-header&quot;]/a[@class=&quot;btn btn-default float-end add-member-button&quot;]</value>
      <webElementGuid>062eb0ed-d165-4699-a02b-aaf03774672d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='project-overview-section']/div/div/div/div/div[5]/div/div/a</value>
      <webElementGuid>f54390e8-920d-4cab-980d-809c038980b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add member')]</value>
      <webElementGuid>03541b57-51ef-4ae5-802e-613407d2dfc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project members'])[1]/following::a[1]</value>
      <webElementGuid>3626fc5e-6c91-4721-9bbd-5e84b1ddcc13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='John Doe'])[2]/preceding::a[2]</value>
      <webElementGuid>ecde7fcf-61f8-4498-b6de-d808d288ed0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/preceding::a[3]</value>
      <webElementGuid>21826e73-705d-4c4f-8711-0a3c682c47e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add member']/parent::*</value>
      <webElementGuid>068229a2-c147-4a05-98de-505dccef4621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[41]</value>
      <webElementGuid>44222911-4af1-4b8e-a2ea-0f4372193ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/a</value>
      <webElementGuid>4eb74f8b-cf18-482b-8ff0-34810f3b3e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Add member' and (text() = ' Add member' or . = ' Add member')]</value>
      <webElementGuid>7111bb94-e260-448b-b7ac-d0200529e2cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
