<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_DeleteMember</name>
   <tag></tag>
   <elementGuidId>905ed5f4-b793-4ecd-b301-7bcf4c823602</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='project-member-table']//a[contains(@class,'delete')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>da1abca9-3ca9-4bb2-a098-338fbd372915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1774799867942</value>
      <webElementGuid>82596ae4-1ab0-4fc1-994b-0651035a8967</webElementGuid>
   </webElementProperties>
</WebElementEntity>
