<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_DeleteFirstProject</name>
   <tag></tag>
   <elementGuidId>32449379-22b8-4324-a1c7-043092f79ff8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='project-table']//tbody//tr[1]//a[contains(@class,'delete')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>2555d957-a0ed-4d35-81d8-da55e98f5af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1774757686542</value>
      <webElementGuid>73039b2b-3c17-4fbd-999a-84c0dbf48960</webElementGuid>
   </webElementProperties>
</WebElementEntity>
