<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_EditFirstProject</name>
   <tag></tag>
   <elementGuidId>e6aa3ddf-be56-4afe-9426-95efeb588e44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='project-table']//tbody//tr[1]//a[contains(@class,'edit')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>3589d491-380e-4423-921a-e6c57c098adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1774716537166</value>
      <webElementGuid>a567b457-7feb-412b-b497-9b0697859c19</webElementGuid>
   </webElementProperties>
</WebElementEntity>
