<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_ConfirmDelete</name>
   <tag></tag>
   <elementGuidId>d41e25b6-503e-473d-9ef7-860fe6d7d0d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmDeleteButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='confirmDeleteButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ac1ea6c4-27c7-4f9e-8d45-e556c8bbe422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmDeleteButton</value>
      <webElementGuid>3fa531ab-3843-495d-8bf0-2d22cef98dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8715f040-cd14-4eff-af6f-5f9a90498f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>b1f8a1b3-d065-46cb-beea-9d811bcc09df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>714ced9e-79bd-42a0-9b21-946a0c630e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>b7313c25-06c9-408c-8201-7ea12c826732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-url</name>
      <type>Main</type>
      <value>https://rise.fairsketch.com/index.php/projects/delete</value>
      <webElementGuid>09c99e02-fcca-4f6b-b7e3-8aab3cad0a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>delete-confirmation</value>
      <webElementGuid>ee899695-1c06-41b4-84c2-d5c36bfc7430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Delete</value>
      <webElementGuid>8e44e4ee-2e54-48fd-9c1d-c3078f635ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmDeleteButton&quot;)</value>
      <webElementGuid>ffa0edd0-7a40-488b-a7f7-01c0ee6d6b4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='confirmDeleteButton']</value>
      <webElementGuid>b8047fc4-d075-4796-8db3-b156756dd614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='confirmationModal']/div/div/div[3]/button</value>
      <webElementGuid>2ce9b211-318d-4321-93af-9ea5486a5fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete?'])[1]/following::button[2]</value>
      <webElementGuid>84372781-a612-4abd-b8fb-3688a81ba2f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>1a40889e-5868-40ec-9dee-24d9ca8d8c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delete']/parent::*</value>
      <webElementGuid>eaadb790-e719-4a37-9116-ae786049d2a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]/button</value>
      <webElementGuid>885bb8a1-0f0a-43a1-af10-26b04c2ef745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'confirmDeleteButton' and @type = 'button' and (text() = ' Delete' or . = ' Delete')]</value>
      <webElementGuid>975f2a8b-e615-4f95-afe4-7c0ad7d44724</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
