<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search</name>
   <tag></tag>
   <elementGuidId>1a6f1d47-6ac7-4eef-9fb5-83587db62dc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dt-search-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dt-search-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e05e295-b01a-44d7-851e-f552aac3f15b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>c21953a3-da67-402b-ac8d-aded00d97379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>d5cc98dc-ef8b-4dfe-bc31-0a85bfded1b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dt-search-0</value>
      <webElementGuid>554d41b5-2e8e-49c1-a710-27c8277f16ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>a9899b94-83ae-4799-b5a4-ff44e9a69644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>project-table</value>
      <webElementGuid>0338a285-fc73-4346-93e9-34fb534a6679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dt-search-0&quot;)</value>
      <webElementGuid>f4b3f4bc-12d4-4b7e-8058-b27faa464a9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dt-search-0']</value>
      <webElementGuid>1bc280ba-5329-49a9-a41f-232f0920c15f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='project-table_wrapper']/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>9080f324-ca1d-437c-8aae-3838b116b17f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>548bdd98-f6d5-4cd9-bd51-702e6bf3cd2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'dt-search-0' and @placeholder = 'Search']</value>
      <webElementGuid>4f50fe88-2c75-44c2-b142-9487940ea202</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
