<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select2_ClientResult</name>
   <tag></tag>
   <elementGuidId>8986d78b-ff5f-41e4-8e78-0a10b757d414</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[contains(@class,'select2-results')]//li[contains(@class,'select2-result')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>f211a4aa-e21e-4f34-8bc8-1cb44cf7be86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1774714554951</value>
      <webElementGuid>c40fc98d-7759-433d-8255-68f737d5648e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
