<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select2_Client</name>
   <tag></tag>
   <elementGuidId>10c86db5-246c-4b4f-9c89-90aaef118dab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='s2id_project_client_id']//a[contains(@class,'select2-choice')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>46b9d546-0a93-47df-9ea5-5ff5bd1ee2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1774714052097</value>
      <webElementGuid>9e9f962e-bab5-4bcf-a992-7831c4e43007</webElementGuid>
   </webElementProperties>
</WebElementEntity>
