<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_ID</name>
   <tag></tag>
   <elementGuidId>84fef9fa-473a-46a1-8167-eebfb09e11cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='project-table']/thead/tr/th/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.dt-column-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0c0085af-842e-43cb-9007-861c476a99b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dt-column-title</value>
      <webElementGuid>cfa91a1c-017a-4dc8-a8ae-5c0d73eab9a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ID</value>
      <webElementGuid>15316185-18c9-426e-bf7b-356aff703871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;project-table&quot;)/thead[1]/tr[1]/th[@class=&quot;w50 dt-orderable-asc dt-orderable-desc dt-type-numeric&quot;]/span[@class=&quot;dt-column-title&quot;]</value>
      <webElementGuid>97c2871a-7243-46a5-9881-fe63013e55f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='project-table']/thead/tr/th/span</value>
      <webElementGuid>afed38a7-eb7f-41ae-b5f9-39ab64f59c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Canceled'])[1]/following::span[1]</value>
      <webElementGuid>fb612568-e2da-461e-ac43-04577671cb90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hold'])[1]/following::span[1]</value>
      <webElementGuid>a1b50fc3-0602-4496-a66d-be1e90edbddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/preceding::span[2]</value>
      <webElementGuid>74a71e77-4136-484e-bbe0-04df70daa07b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client'])[1]/preceding::span[4]</value>
      <webElementGuid>8815f534-53c1-46c2-a1d2-63513e163272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ID']/parent::*</value>
      <webElementGuid>6c471853-cb52-481b-a6a7-a2e10c407428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/span</value>
      <webElementGuid>7d0ac13b-ba49-43a5-a5c3-6ddc2910abf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ID' or . = 'ID')]</value>
      <webElementGuid>64aa2e1c-dbac-46f7-b71f-9b5346614380</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
