<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_DeleteFirstClient</name>
   <tag></tag>
   <elementGuidId>869948a1-fc90-4e44-844a-a9bda350d220</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='client-table']//tbody//tr[1]//a[contains(@class,'delete')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>5e75bb9a-9d82-40e1-8ddf-1698ffdeeb43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1774795276944</value>
      <webElementGuid>dd6fb85a-2c90-4bfc-8af2-64277b7d1f14</webElementGuid>
   </webElementProperties>
</WebElementEntity>
