<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_FilterDropdown</name>
   <tag></tag>
   <elementGuidId>324c0eef-013d-495e-9cd7-d459bd0fe629</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-default.smart-filter-dropdown.dropdown-toggle.caret</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b14dabea-5faa-4b89-8010-fc8f495da4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default smart-filter-dropdown dropdown-toggle caret</value>
      <webElementGuid>d0420741-2d02-45a8-abc4-0593ef73f4e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>47acc26f-0bf3-42c6-9d68-fe0b8b459b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>f5a4f0a4-35fc-494e-83b4-9cd3cd3e27cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>938f5fb0-b742-495e-af8d-e3e6e1667d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filters</value>
      <webElementGuid>2bf93bb7-541d-4f7e-825c-3b1aac021cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client-table_wrapper&quot;)/div[@class=&quot;filter-section-container&quot;]/div[@class=&quot;filter-section-flex-row&quot;]/div[@class=&quot;filter-section-left&quot;]/div[@class=&quot;filter-item-box smart-filter-dropdown-box&quot;]/div[@class=&quot;dropdown smart-filter-dropdown-container&quot;]/button[@class=&quot;btn btn-default smart-filter-dropdown dropdown-toggle caret&quot;]</value>
      <webElementGuid>20254f87-7de3-4029-b1ee-d01d43877237</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>4221b5f4-97b6-4cbe-b3b6-0887534bbaf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='client-table_wrapper']/div/div/div/div[2]/div/button</value>
      <webElementGuid>24a96183-66a0-4705-afc0-d1031f7926be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Filters'])[1]/preceding::button[1]</value>
      <webElementGuid>40aa973e-93e8-4c05-b814-35b5a21a4558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Has due'])[2]/preceding::button[2]</value>
      <webElementGuid>e1b524e1-2f43-45aa-84be-aac58f074f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Filters']/parent::*</value>
      <webElementGuid>ce2c0140-bf1e-4599-a890-b97352a1c29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div/div[2]/div/button</value>
      <webElementGuid>97d8899a-4a3e-44f0-97a2-2986bf154e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Filters' or . = 'Filters')]</value>
      <webElementGuid>5a1e11fb-fa2a-452f-a254-0c100f1a4e96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
