<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Filter_HasOpenProjects</name>
   <tag></tag>
   <elementGuidId>087dbb88-d04f-498c-89c3-36bc4c9145f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>294c0da0-3135-4e22-87ea-8b2d1565819c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default bookmarked-filter-button round</value>
      <webElementGuid>cd4df55a-3aa8-453b-a69f-20931c67ef45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0b19b60e-16e1-482f-955a-4bce2aef8fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>gyjjmpetoj</value>
      <webElementGuid>9649722c-87e9-4432-8784-42be3bb78c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Has open projects</value>
      <webElementGuid>9dece22f-7411-4d3b-9ddf-3f73ea676d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client-table_wrapper&quot;)/div[@class=&quot;filter-section-container&quot;]/div[@class=&quot;filter-section-flex-row&quot;]/div[@class=&quot;filter-section-left&quot;]/div[@class=&quot;bookmarked-filter-button-container scrollable-container&quot;]/div[@class=&quot;filter-item-box bookmarked-filter-button-wrapper&quot;]/button[@class=&quot;btn btn-default bookmarked-filter-button round&quot;]</value>
      <webElementGuid>186e0436-7435-49cf-8442-4a576d919752</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>c29d86f0-3f48-4b67-96b4-d04c46efb447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='client-table_wrapper']/div/div/div/div[4]/div[2]/button</value>
      <webElementGuid>959bb14d-a69e-4fbb-8ba1-79cc98c0f0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Has due'])[2]/following::button[1]</value>
      <webElementGuid>1d9cd6b3-5760-4c85-bb5a-adcb6f5cddfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Filters'])[1]/following::button[3]</value>
      <webElementGuid>ab2a6dab-3b68-4a6e-96b9-dd5681417f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Clients'])[2]/preceding::button[1]</value>
      <webElementGuid>a40e4c9f-620d-46ed-81a5-e699257784fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batch update'])[1]/preceding::button[4]</value>
      <webElementGuid>ea7f8acf-5865-4cd1-9acb-47f98f5be7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>c47ef3be-3ce9-4a91-9fc5-eee4cc16afad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Has open projects' or . = 'Has open projects')]</value>
      <webElementGuid>1848962e-61fd-476e-bc89-486019de16e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
