<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_AddEvent</name>
   <tag></tag>
   <elementGuidId>d82c8228-4027-43fd-804e-044e84bde9f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-default.add-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content']/div/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3cb1a8ae-33f2-4398-94e5-ff05f2443780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>b87081d7-2cd6-4c3c-871b-9da3eede438c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default add-btn</value>
      <webElementGuid>9caeaeb8-47ec-4a63-90d4-916bd94063c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add event</value>
      <webElementGuid>22e6dcb4-1eb4-40b4-a999-c9da00eef5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-act</name>
      <type>Main</type>
      <value>ajax-modal</value>
      <webElementGuid>b544e950-96f6-4a84-85d7-3eb223bbc6dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Add event</value>
      <webElementGuid>0a344224-4d36-4f91-8cc4-fe029758be3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-url</name>
      <type>Main</type>
      <value>https://rise.fairsketch.com/index.php/events/modal_form</value>
      <webElementGuid>f776c561-ef8b-47c5-a679-596b4ae2517f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add event</value>
      <webElementGuid>cb54439b-c873-4ce9-bac1-0830928b7a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;card xs-full-width-button&quot;]/div[@class=&quot;page-title clearfix&quot;]/div[@class=&quot;title-button-group custom-toolbar events-title-button skip-dropdown-migration&quot;]/a[@class=&quot;btn btn-default add-btn&quot;]</value>
      <webElementGuid>6169e25b-0c22-4ab6-bd26-41265f94ae15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/div/div/div/a[2]</value>
      <webElementGuid>551cf6ba-8e53-46ec-b443-4b796296c4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Add event')])[2]</value>
      <webElementGuid>544b75e6-fa8b-437a-ad93-19538a258d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project deadline'])[1]/following::a[2]</value>
      <webElementGuid>c0fa7d57-5712-47dc-91df-38567004dbf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project start date'])[1]/following::a[2]</value>
      <webElementGuid>7f0584db-6fa0-4edf-beac-ae5533745f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='today'])[1]/preceding::a[5]</value>
      <webElementGuid>287db8db-f0cd-4b0f-9618-7327cbe067f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='March 2026'])[1]/preceding::a[5]</value>
      <webElementGuid>da8c0f83-e9d8-489c-a187-92786b1d94f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[33]</value>
      <webElementGuid>ff56e938-854b-43c3-9b77-20c9e05dd18d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/a[2]</value>
      <webElementGuid>d20f501c-7400-4c9c-9021-f9ffa2c91044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Add event' and (text() = ' Add event' or . = ' Add event')]</value>
      <webElementGuid>2a2a0ee8-5545-453f-b610-d25d51bfbc2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
