<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_SpecificMembers</name>
   <tag></tag>
   <elementGuidId>9dbf50d7-8b40-4ef3-b27a-7aec545ed59e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#specific_members_and_teams</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='specific_members_and_teams']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>928c0d8b-c35e-49c0-bd95-3395954e432c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>96e546b5-58e4-46de-a04f-945e15bad709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>specific_members_and_teams</value>
      <webElementGuid>d32fafeb-2a11-480f-a87c-eac5829f8b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>specific_members_and_teams</value>
      <webElementGuid>05031a94-cef0-4a62-beb4-797ef3c80df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input sharing-option-checkbox</value>
      <webElementGuid>4900ce7d-938d-4e88-bc5f-79de4250e298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-show-if-not-checked</name>
      <type>Main</type>
      <value>all_members</value>
      <webElementGuid>299316f0-765a-4be2-8523-e50384bbc2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;specific_members_and_teams&quot;)</value>
      <webElementGuid>249cb08e-9be0-41da-874f-d61a2a9e913e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='specific_members_and_teams']</value>
      <webElementGuid>adeed35c-5b18-49a3-8b44-1fcf9ef0c1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sharing-options-container']/div[3]/input</value>
      <webElementGuid>060e4fb8-bf88-4410-b951-7dc679ceb2a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>17ef0dc0-5c03-48cd-9f02-6d9bbfc951b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'specific_members_and_teams' and @id = 'specific_members_and_teams']</value>
      <webElementGuid>910f9711-5fbe-4007-ae2c-780dbd05e659</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
