<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>datepicker_Today</name>
   <tag></tag>
   <elementGuidId>8b1e5a20-3cee-44ca-ad03-4d28755963aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='datepicker-days']//td[contains(@class,'today')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>09a43ec5-45e7-48bc-9c8a-a70cca809a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1774776031375</value>
      <webElementGuid>ce3f8687-9e41-42db-9f28-af5f50368cf3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
