<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>heading_EventDetails</name>
   <tag></tag>
   <elementGuidId>b8fcc5e5-ec18-441f-8888-6a6a28de74f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ajaxModalTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='ajaxModalTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>c8f04404-c794-4359-88cf-a7cb781e62cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>7d36f005-3cac-4059-ada4-60ea8b232374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ajaxModalTitle</value>
      <webElementGuid>f036428b-fd63-40c0-9f16-1d4890932aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>RISE - Ultimate Project Manager and CRM</value>
      <webElementGuid>7b46d198-0c15-4a4a-a364-29f7f290afdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Event details</value>
      <webElementGuid>d383a32a-2320-49a4-91cd-f70a35178d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ajaxModalTitle&quot;)</value>
      <webElementGuid>849f9573-bd02-443a-98fb-102bb39d0e0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='ajaxModalTitle']</value>
      <webElementGuid>adc379f0-a7af-4638-977e-7706587ee085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajaxModal']/div/div/div/h4</value>
      <webElementGuid>c4b184fa-ee03-4d05-819a-49dbf0916c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Industry Panel Discussion'])[1]/following::h4[1]</value>
      <webElementGuid>822190ea-0d48-4d4c-9836-3616e002629a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Anniversary Celebration'])[1]/following::h4[1]</value>
      <webElementGuid>7a72b846-8df6-4c81-b69a-3690842868db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Event details']/parent::*</value>
      <webElementGuid>7cded11f-af69-42e7-82e6-47accbaddb10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>26a1b0c4-6ba9-4170-bdef-4cdecf25969d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'ajaxModalTitle' and (text() = 'Event details' or . = 'Event details')]</value>
      <webElementGuid>c831881d-fa48-4967-b6f2-e3e9d9bb195f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
