<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ReminderTime</name>
   <tag></tag>
   <elementGuidId>a647e2d1-81cb-49bd-b85a-f340d6359580</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#event-start_time</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='event-start_time']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35dde2a4-1e7e-4a40-8d33-e6804c0a7960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>564cb2bb-6518-460b-b62d-aac08f96817b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>start_time</value>
      <webElementGuid>aac99946-e232-4fea-a15c-5df28b9069ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>event-start_time</value>
      <webElementGuid>c12b4da4-f616-4b5c-9710-b7782154bb71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>43e21188-04a7-4aea-8e6b-3d800ec1e74b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Time</value>
      <webElementGuid>f21e69f1-b6ea-46f2-af3e-77af1333f86e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0dcac6a1-4ddf-4a32-bf61-06b9709ea880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg-required</name>
      <type>Main</type>
      <value>This field is required.</value>
      <webElementGuid>28e905c7-8b7c-421d-9862-962b8e28cbcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;event-start_time&quot;)</value>
      <webElementGuid>701b25bd-0503-4275-bc0a-48dbd9269a7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='event-start_time']</value>
      <webElementGuid>d1876e0e-5905-4bd3-ade4-992c9e57ec7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='event-reminder_form']/div[2]/div/div[2]/input</value>
      <webElementGuid>dbf74b75-2e9e-44d8-a106-43f9424d0eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>0288d9dc-0e54-4146-9e3e-0839f0b95f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'start_time' and @id = 'event-start_time' and @placeholder = 'Time']</value>
      <webElementGuid>65a50589-a12b-43cf-862a-2f4083f778b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
