<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_ReminderTitleError</name>
   <tag></tag>
   <elementGuidId>b766c990-b0f9-45f9-a23f-a01b141715ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#event-title-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='event-title-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>17f0efb7-510e-43d6-9739-d3355934882e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>event-title-error</value>
      <webElementGuid>fcc125a6-8aaa-4bd6-8893-b428f8b6ef7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help-block</value>
      <webElementGuid>0c7ba4fc-c8a9-48ee-beaf-898aabe46c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This field is required.</value>
      <webElementGuid>54c80acd-188a-43fb-8743-471dc4a719e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;event-title-error&quot;)</value>
      <webElementGuid>c050f383-a62e-4cc9-9869-bc72524c3eec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='event-title-error']</value>
      <webElementGuid>9b3d77c1-a57b-4ce5-98cf-37baa903f7d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='event-reminder_form']/div/div/span</value>
      <webElementGuid>35184352-a6b3-4607-9bfd-f5306cf8d3ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add reminder'])[1]/following::span[1]</value>
      <webElementGuid>185927b8-1620-471b-b542-bbb65a5a6d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reminders (Private):'])[1]/following::span[1]</value>
      <webElementGuid>69c6ae0a-88ee-4952-96ed-06ed1f7d8ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required.'])[2]/preceding::span[1]</value>
      <webElementGuid>2ef4d18e-635b-47b7-a4ac-34279fe85fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required.'])[3]/preceding::span[2]</value>
      <webElementGuid>0e113b3a-878e-46e9-aec0-7f557633c09d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This field is required.']/parent::*</value>
      <webElementGuid>c562a3e4-fbdc-414b-bd20-2e57a3743f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/span</value>
      <webElementGuid>e1c27778-bdaa-4d94-aa51-ec94141406d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'event-title-error' and (text() = 'This field is required.' or . = 'This field is required.')]</value>
      <webElementGuid>b8e883bd-a2ef-4489-8e80-263bda779cbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
