<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_EditEvent</name>
   <tag></tag>
   <elementGuidId>921a35b0-137d-4357-8b2a-e64ab11eeb15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ajaxModalContent']/div[2]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fc9b01ec-61b4-4291-b9c7-0ef43b5d6b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>d6b96b0a-b479-4322-b3e3-b8fc94883849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>e124a1cb-a532-4bad-9f9a-a640ecf030c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-post-encrypted_event_id</name>
      <type>Main</type>
      <value>980f0ec85820d261935d0732072ccfe63764e2b97ccbd6da8fcfe3988a836e449f05b59f3967f22ff8bc5cd0fbd6308cb6b1f7c5fba30c773750c137a6abbbe6a68227fc06ddd2680e85748222b6933065c80db9f33e4d1bcdc8c2</value>
      <webElementGuid>36fc53ce-2f91-4fc0-924c-4776bf4d843e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Edit event</value>
      <webElementGuid>1f558e8f-7458-4b06-96e7-23eac634ddfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-act</name>
      <type>Main</type>
      <value>ajax-modal</value>
      <webElementGuid>d0a5b7ea-f112-47a8-9356-f5044b57f097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Edit event</value>
      <webElementGuid>e0bdab4a-7543-4f1d-a75e-6ac2737443c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-url</name>
      <type>Main</type>
      <value>https://rise.fairsketch.com/index.php/events/modal_form</value>
      <webElementGuid>91241569-f50d-4ff4-b305-4bd1ab945bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Edit event</value>
      <webElementGuid>27810cc5-8bf4-4d03-9473-03816337133f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ajaxModalContent&quot;)/div[@class=&quot;modal-footer&quot;]/a[@class=&quot;btn btn-default&quot;]</value>
      <webElementGuid>ea3266a6-8074-470a-9903-6e6c813f35de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajaxModalContent']/div[2]/a[2]</value>
      <webElementGuid>4b2cf372-f0a5-4946-ad29-cd8bebd4ecaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit event')]</value>
      <webElementGuid>12d25e90-0633-485b-b23b-9e8c5cd871a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No record found.'])[1]/following::a[2]</value>
      <webElementGuid>e305e4be-dd77-4bd9-94f8-757fd86daa4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/following::a[2]</value>
      <webElementGuid>ecad4fd0-8e1a-4f93-a3a6-c61d12f85a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::a[1]</value>
      <webElementGuid>9ccfc822-ce1b-4fcb-88ae-f01bece880a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/preceding::a[1]</value>
      <webElementGuid>963bba5d-d28c-43fc-a3d8-009929b73c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit event']/parent::*</value>
      <webElementGuid>549bbb9a-49ea-4afa-941c-b732198af427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[39]</value>
      <webElementGuid>05731dbb-d203-409e-bb6b-2d32f3446007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[2]</value>
      <webElementGuid>c239655f-12ce-4730-b6f9-c5fdfaea5d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Edit event' and (text() = ' Edit event' or . = ' Edit event')]</value>
      <webElementGuid>0f1228b0-3bc4-40c5-9577-13683ab9af9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
