<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_DeleteEvent</name>
   <tag></tag>
   <elementGuidId>b1862478-3eed-42b1-8cd3-a196ab4189d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#delete_event</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='delete_event']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4a9e1775-5906-493f-bb93-993d583c81e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>e96c9237-2c56-4656-8c27-53f85f7e7a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default float-start</value>
      <webElementGuid>fc35c0a1-6532-4fed-aff9-e54752bbc1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delete_event</value>
      <webElementGuid>7ae1e035-fe84-47a8-b1e1-03357b184fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-encrypted_event_id</name>
      <type>Main</type>
      <value>e721c3f210748597e885636aa69c3003578f282ac04f4f1f6964230fe6fbaac4f63d5919fefa724d5eb52aaeb29c65e52d0d5da0f42af97b6ad9d8959cde4c6dd0f9f193c760b499ebe8f4d83e68ccc5d581cf9d30045fab57929f</value>
      <webElementGuid>17b707e7-fa6c-4e66-bb0a-374b3366b1c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Delete event</value>
      <webElementGuid>8f776e7b-b0f6-492e-91ea-3eca92244d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delete_event&quot;)</value>
      <webElementGuid>059a564d-4767-44b3-a446-69681b9f9c28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='delete_event']</value>
      <webElementGuid>a63b11b6-547f-44c4-8d6c-c634cafb5cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajaxModalContent']/div[2]/a</value>
      <webElementGuid>107860d8-62e3-4a7b-8f8b-8854fdc9bffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Delete event')]</value>
      <webElementGuid>bffb928a-0fbe-41d5-aea7-39aab336f3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No record found.'])[1]/following::a[1]</value>
      <webElementGuid>5ff677ff-af86-4ab4-8040-dad6ac219fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/following::a[1]</value>
      <webElementGuid>2f43d6ce-2630-41e5-b63a-be0442cf8562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::a[2]</value>
      <webElementGuid>bd8ed51a-84e2-467a-8338-9c33c2703ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/preceding::a[2]</value>
      <webElementGuid>111efd2d-9dc0-40e8-bdf4-5abc79d20303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delete event']/parent::*</value>
      <webElementGuid>c93ba4e8-08bf-4747-9c30-1d48543db6e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[38]</value>
      <webElementGuid>8dec1530-ca87-4828-b600-a4f5f84a2687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div[2]/a</value>
      <webElementGuid>fec1541e-494a-4e7d-a8ff-d993a2f57c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'delete_event' and (text() = ' Delete event' or . = ' Delete event')]</value>
      <webElementGuid>951f814a-319e-480b-9ce7-b926fceb4429</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
