<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_AddReminder</name>
   <tag></tag>
   <elementGuidId>28cf8b98-cfa6-4a7b-abc6-8e21892e4b11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#event-show-add-reminder-form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='event-show-add-reminder-form']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>18d38bb1-59ea-4399-b72d-a67d82cbc32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>ffbd63ab-b77c-48f3-beeb-2f8b170f9fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>event-show-add-reminder-form</value>
      <webElementGuid>279271a1-b309-4029-9aa1-1df7e8a5f2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add-reminder-btn</value>
      <webElementGuid>f34eecef-ecd1-426b-9336-3d5bc46345fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add reminder</value>
      <webElementGuid>e55fa6fb-9b4b-47d5-b35e-570b5b801b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;event-show-add-reminder-form&quot;)</value>
      <webElementGuid>3d9bfe97-13ba-4371-b1bb-84af0d594687</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='event-show-add-reminder-form']</value>
      <webElementGuid>e291f689-4d2d-46d5-92ff-07c30c6d5f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='event-reminders']/a</value>
      <webElementGuid>7bd115fd-d3ea-40b3-8c58-4c7641b790c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add reminder')]</value>
      <webElementGuid>a7739c8a-8bfa-408e-95f0-c670fd434597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reminders (Private):'])[1]/following::a[1]</value>
      <webElementGuid>592b571e-9284-4160-9856-a69bd638aa58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='John Doe'])[2]/following::a[1]</value>
      <webElementGuid>98641587-5f7d-4dcc-b04f-9b022ee339da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Repeat'])[1]/preceding::a[1]</value>
      <webElementGuid>9e44ecb7-2ddf-4651-9d10-45f34a10344b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Repeat every'])[1]/preceding::a[1]</value>
      <webElementGuid>61c84f3c-d2bf-47a6-9b70-ae860694cb9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add reminder']/parent::*</value>
      <webElementGuid>ee656283-7967-4c9d-8093-ceab190614b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:;')]</value>
      <webElementGuid>a691cba9-d69f-48cb-b72a-48afde9c65f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/a</value>
      <webElementGuid>1a5aa65e-4270-4c01-802a-143ff59b1cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and @id = 'event-show-add-reminder-form' and (text() = ' Add reminder' or . = ' Add reminder')]</value>
      <webElementGuid>d7ba95c2-6e71-42e9-beb1-766bb0776dbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
