<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select2_ShareResult</name>
   <tag></tag>
   <elementGuidId>6c9890fe-618b-4ac5-bbeb-a8d80499567f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[contains(@class,'select2-results')]//li[contains(@class,'select2-result')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>bcb68405-6fd1-4464-aa22-27af7020e55c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1774774298148</value>
      <webElementGuid>efb396a2-718f-451a-b3a2-f0e54a66dc9b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
