<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_AddContact</name>
   <tag></tag>
   <elementGuidId>100660f0-7a1f-4a4f-8dcf-b7c7f5bcaebc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='client-view-contacts-section']/div/div/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>65f6d789-c37e-4ab5-b573-77e6578dc5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>d7b7731f-d82b-4ee3-80f9-b31383ab0861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p10</value>
      <webElementGuid>8597cb64-f6fa-4ead-b636-8f307fb6e9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add contact</value>
      <webElementGuid>f7258722-1486-410d-a4ec-d456756f21e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-post-client_id</name>
      <type>Main</type>
      <value>101</value>
      <webElementGuid>6af438eb-c579-471d-8e15-b4693d844cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-act</name>
      <type>Main</type>
      <value>ajax-modal</value>
      <webElementGuid>9d655e88-1567-44c4-abeb-5a81ca3608ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Add contact</value>
      <webElementGuid>88f53c07-ab27-4573-b129-83a862f194c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-url</name>
      <type>Main</type>
      <value>https://rise.fairsketch.com/index.php/clients/add_new_contact_modal_form</value>
      <webElementGuid>b429be0b-5724-4dd6-a7c4-9f6cc80686b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add contact</value>
      <webElementGuid>239f6a39-83c1-4063-adca-30d58f143481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client-view-contacts-section&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;card-header border-bottom-0&quot;]/div[@class=&quot;card-header-button float-end&quot;]/a[@class=&quot;p10&quot;]</value>
      <webElementGuid>b75c6af5-1e49-4e56-b0c5-9639a7343afb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='client-view-contacts-section']/div/div/div/a[2]</value>
      <webElementGuid>b63064a0-7f98-4a52-a643-4a7ff57a4761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add contact')]</value>
      <webElementGuid>a18410f2-ab8f-4895-9eb8-2c07580bf339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due'])[1]/following::a[2]</value>
      <webElementGuid>51c5069a-304d-45f7-810d-2819b5ce9646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/preceding::a[1]</value>
      <webElementGuid>fa73d398-4249-4578-ad06-fcf6046f23d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::a[1]</value>
      <webElementGuid>b3431d7c-f4d2-4ca7-a92a-12f5d746f311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add contact']/parent::*</value>
      <webElementGuid>7ad10cdf-672a-4c37-a473-051b2bbd30c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[34]</value>
      <webElementGuid>d0a88cff-6667-4063-aed5-10c957410b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/a[2]</value>
      <webElementGuid>4837fca0-d212-4694-ae80-3c06ff4c7f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Add contact' and (text() = ' Add contact' or . = ' Add contact')]</value>
      <webElementGuid>1a93eaf6-5236-49a9-b096-87fec3e85380</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
