<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_FirstContact</name>
   <tag></tag>
   <elementGuidId>7f953806-49c3-49df-a41a-f7794879396f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='client-view-contacts-section']//a[contains(@href,'contact_profile')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>a81fa3c3-5860-45a3-8d5b-b89f1568c576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1774887890563</value>
      <webElementGuid>0f9270b9-3cd0-49ed-aaa1-774ec360e793</webElementGuid>
   </webElementProperties>
</WebElementEntity>
