<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_FilterDropdown</name>
   <tag></tag>
   <elementGuidId>4457fde4-6399-4079-bc41-9449e0b86030</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-default.smart-filter-dropdown.dropdown-toggle.caret.show</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6cac6a6e-d586-4cca-9b22-55fb36031df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default smart-filter-dropdown dropdown-toggle caret show</value>
      <webElementGuid>022a0f22-84b4-462e-972d-e0200ecad08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>264f32bf-215f-4195-856d-9a2ce96bf203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>f588dbf9-d8bd-482d-b5f4-50f7ef3eddcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>80fe4f23-f43c-48d2-a651-8b41922e788f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All tasks</value>
      <webElementGuid>ba40b00d-5dde-4693-996c-895a6d4c7e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task-table_wrapper&quot;)/div[@class=&quot;filter-section-container&quot;]/div[@class=&quot;filter-section-flex-row&quot;]/div[@class=&quot;filter-section-left&quot;]/div[@class=&quot;filter-item-box smart-filter-dropdown-box&quot;]/div[@class=&quot;dropdown smart-filter-dropdown-container&quot;]/button[@class=&quot;btn btn-default smart-filter-dropdown dropdown-toggle caret show&quot;]</value>
      <webElementGuid>4cb2e27d-fcae-48ef-91f6-3162758ecb27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>04dcf751-604b-4cd6-8e76-87fdff8d43bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='task-table_wrapper']/div/div/div/div[2]/div/button</value>
      <webElementGuid>066459b5-6d70-4a05-9790-94578d91a527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gantt'])[1]/following::button[2]</value>
      <webElementGuid>2ea6f6e0-8b37-424b-bc68-c65b3c707b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kanban'])[1]/following::button[2]</value>
      <webElementGuid>cdb8fa96-866d-40f4-83aa-6a49d3c67d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Filters'])[1]/preceding::button[1]</value>
      <webElementGuid>7be66d9b-b6e0-4d7a-a54f-8d109e55af0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All tasks'])[3]/preceding::button[2]</value>
      <webElementGuid>4d8f0497-ea58-412e-af58-5063de95ced1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All tasks']/parent::*</value>
      <webElementGuid>28662ea0-dfd1-4b06-bec9-4fdf4d61b0fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div/div/div/div[2]/div/button</value>
      <webElementGuid>ae7dcb2f-a048-4030-a934-d703971b7137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'All tasks' or . = 'All tasks')]</value>
      <webElementGuid>73329bca-e1d1-47f9-b5e1-d6efd4668a0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
