<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_ClearFilter</name>
   <tag></tag>
   <elementGuidId>91057a63-b288-4266-84dc-acbb939c3746</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='task-table_wrapper']/div/div/div/div[2]/div/div/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.inline-block.btn.btn-default.clear-filter-button.ml10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>00b9b7de-5135-4dfa-bbb6-86e6af0e7bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-block btn btn-default clear-filter-button ml10</value>
      <webElementGuid>1c1989d4-6f2f-4c86-99c7-6d4855b1bd2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>3e7ff7ca-fa96-4b9b-8943-b634c566f624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clear</value>
      <webElementGuid>15475827-d2b1-41f2-be2f-6b1144f34e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task-table_wrapper&quot;)/div[@class=&quot;filter-section-container&quot;]/div[@class=&quot;filter-section-flex-row&quot;]/div[@class=&quot;filter-section-left&quot;]/div[@class=&quot;filter-item-box smart-filter-dropdown-box&quot;]/div[@class=&quot;dropdown smart-filter-dropdown-container&quot;]/div[@class=&quot;dropdown-menu w300 show&quot;]/div[@class=&quot;pb10 pl10&quot;]/a[@class=&quot;inline-block btn btn-default clear-filter-button ml10&quot;]</value>
      <webElementGuid>2741865a-e52a-484d-b616-543fe61cf8f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='task-table_wrapper']/div/div/div/div[2]/div/div/div/a[2]</value>
      <webElementGuid>012e5e23-ffd7-40b8-91db-2edb28a6b3df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Clear')]</value>
      <webElementGuid>ffa43c27-b7d6-4144-900a-fdf82e01b541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Filters'])[1]/following::a[1]</value>
      <webElementGuid>0d3c6153-ea03-4a6c-9ecd-b0eb666844b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All tasks'])[1]/following::a[2]</value>
      <webElementGuid>2cf3916c-a79f-407e-88e8-d7ebf1af055f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All tasks'])[3]/preceding::a[7]</value>
      <webElementGuid>d020bb47-3d03-4d13-8b39-5d1d0d052344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bug'])[2]/preceding::a[7]</value>
      <webElementGuid>a3a144a5-809a-4384-96a1-dfb73418d153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Clear']/parent::*</value>
      <webElementGuid>4840a59d-d4eb-47bd-9b2b-638c46c22ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[36]</value>
      <webElementGuid>41be1852-3095-4635-bbfa-d4277651492f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a[2]</value>
      <webElementGuid>aa23132f-b546-48b3-b077-8c9fe6f7c53f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Clear' or . = 'Clear')]</value>
      <webElementGuid>16cc1f14-1300-4bd8-84a3-28157db32a8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
