<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_RecentlyUpdated</name>
   <tag></tag>
   <elementGuidId>8700fba8-3eff-48c3-83d2-4d1b227ed291</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0427a635-4e09-4a98-a020-08caa8f65553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default bookmarked-filter-button round</value>
      <webElementGuid>ca5e0440-6b7c-40f3-887c-a6b3000008a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>30b51410-ebbe-46e1-a888-d9bc0bc6f95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>xgvxgnwpnv</value>
      <webElementGuid>f354b8d1-7792-4883-99cb-b95b01e56bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recently Updated</value>
      <webElementGuid>40c0d12b-d5d7-4906-8bcb-fbae292844ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task-table_wrapper&quot;)/div[@class=&quot;filter-section-container&quot;]/div[@class=&quot;filter-section-flex-row&quot;]/div[@class=&quot;filter-section-left&quot;]/div[@class=&quot;bookmarked-filter-button-container scrollable-container&quot;]/div[@class=&quot;filter-item-box bookmarked-filter-button-wrapper&quot;]/button[@class=&quot;btn btn-default bookmarked-filter-button round&quot;]</value>
      <webElementGuid>301426a0-a7d0-4882-826e-3afa54e464d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[8]</value>
      <webElementGuid>e5edf9fb-43d0-4c07-b1b5-f2ef3f0fc431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='task-table_wrapper']/div/div/div/div[4]/div[6]/button</value>
      <webElementGuid>77c3bd1e-5e42-4dd0-a141-372988b218c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Tasks'])[2]/following::button[1]</value>
      <webElementGuid>c78e9b7b-4c24-4125-bce6-db279bb70686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bug'])[2]/following::button[4]</value>
      <webElementGuid>85320507-2253-4088-bec7-99e7534ca784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batch update'])[1]/preceding::button[2]</value>
      <webElementGuid>34ff5f86-c05b-48ce-aae8-94c83d00b52c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete selected items'])[1]/preceding::button[2]</value>
      <webElementGuid>f8eacfa3-aabd-4116-83aa-fa7ef323ed8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button</value>
      <webElementGuid>07a04880-fcfb-4ac5-b2fb-842d7ac240bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Recently Updated' or . = 'Recently Updated')]</value>
      <webElementGuid>ceb350f5-374d-41cc-ba81-b5996ba51db8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
