<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_EditFirstTask</name>
   <tag></tag>
   <elementGuidId>9754670c-b454-41ef-9b0f-57acb8d7a91d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='task-table']//tbody//tr[1]//a[contains(@class,'edit')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>e3fe70ce-e843-4b47-b48c-7228054227a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1774802325759</value>
      <webElementGuid>23e30bb2-1605-4c88-bc2c-529b9c9c8b8f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
