<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select2_StatusResult</name>
   <tag></tag>
   <elementGuidId>f97fc4d6-e97f-4945-956f-65c0eff14e24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[contains(@class,'select2-results')]//li[contains(@class,'select2-result')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>3783d822-77e7-4bfa-8a43-6099770ee524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1774802363625</value>
      <webElementGuid>1dd57d04-511c-41ad-a617-32ac960b1ec8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
