<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select2_AssignTo</name>
   <tag></tag>
   <elementGuidId>4cc404d7-3576-48a4-ad54-4f264eec891f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='s2id_assigned_to']//a[contains(@class,'select2-choice')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>a354a89b-e26a-4058-90fc-30c9e1c86aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1774800789728</value>
      <webElementGuid>fdd08856-c58c-457e-b610-6cbd49b28454</webElementGuid>
   </webElementProperties>
</WebElementEntity>
