<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select2_AssignToResult</name>
   <tag></tag>
   <elementGuidId>7d877ff4-59b2-4e25-9f91-8aee6b5934c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[contains(@class,'select2-results')]//li[contains(@class,'select2-result')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>73da7780-b4fc-4e0e-bdf0-edea394f98e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1774800807321</value>
      <webElementGuid>ec73f372-dcbf-48ae-b6d8-3e56c8d8c536</webElementGuid>
   </webElementProperties>
</WebElementEntity>
