<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_DeleteFirstLead</name>
   <tag></tag>
   <elementGuidId>9e062d54-a2f9-4e30-b81b-5f2d4ec06a41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='lead-table']//tbody//tr[1]//a[contains(@class,'delete')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>6b7c116b-1c9d-4c5b-9909-510136f1616d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1774798786999</value>
      <webElementGuid>854a4b4b-894f-4855-96e3-5ab760bbb143</webElementGuid>
   </webElementProperties>
</WebElementEntity>
