<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CompanyName</name>
   <tag></tag>
   <elementGuidId>792257c2-2140-46b6-b50b-04c5b6d1a84c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#company_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='company_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e42b985e-6e4c-422b-b372-955f73dc0a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f21b0edd-5821-49e5-9038-378f33ca99ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>company_name</value>
      <webElementGuid>425e329a-684b-4fea-a4bd-90195fc48c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>company_name</value>
      <webElementGuid>619313c0-9478-4c0a-abe8-ec9603283420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control company_name_input_section</value>
      <webElementGuid>d8b7d349-8dc5-4f15-98e9-b43e3d29d024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Company name</value>
      <webElementGuid>cbc21ca6-87a4-4bae-b3fe-2734b7091ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg-required</name>
      <type>Main</type>
      <value>This field is required.</value>
      <webElementGuid>dea3af45-38c9-4fa7-9944-ca7cd3afee3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;company_name&quot;)</value>
      <webElementGuid>5599d0a2-efdc-4933-ae5d-0932b5c19737</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='company_name']</value>
      <webElementGuid>fd31f527-3775-4ab2-b49c-fa3fa98c61fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ynputhzg']/div/div[2]/div/div/input</value>
      <webElementGuid>7dff6b52-f4e9-4e4e-b36f-f7ff0eed4ed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/div/div/input</value>
      <webElementGuid>0aa60de7-98ee-43b5-b823-e8d868d73003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'company_name' and @id = 'company_name' and @placeholder = 'Company name']</value>
      <webElementGuid>72af8fdf-b7b8-4eb7-a906-34879b3f137e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
