<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select2_StatusResult</name>
   <tag></tag>
   <elementGuidId>ef6b97ba-e5fb-445f-a192-5bb4d5c971cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[contains(@class,'select2-results')]//li[contains(@class,'select2-result')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>5681201a-1e9d-41df-bdaa-cf69878ff7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1774798075125</value>
      <webElementGuid>a4b67274-ec9c-4d58-820a-2e5d5af24ec3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
