<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_CreatedAt</name>
   <tag></tag>
   <elementGuidId>11a87dd8-6b99-4561-94e2-ef9a64068892</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='lead-table']//th//span[contains(text(),'Created at')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>faf7c337-1089-49a1-822a-f064dbe5d3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1774797798387</value>
      <webElementGuid>1eb01538-d8ee-4f36-90da-b6c507ad1a18</webElementGuid>
   </webElementProperties>
</WebElementEntity>
