<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_CreatedAt_Desc</name>
   <tag></tag>
   <elementGuidId>7a29b08f-87a0-4481-bc7b-5a1a172d7b39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='lead-table']//th[contains(@class,'dt-ordering-desc')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>c2b50c42-40ec-4679-aaef-2b2b779eb786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1774798002210</value>
      <webElementGuid>26e87afc-cc34-445e-bf88-94102fd035e5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
